### ISSUE TITLE
Jump tests?

### ISSUE THREAD

**Issue by waynelapierre** [algoquant/HighFreq#2]
I find this R package very interesting. Have you considered adding jump tests such as the Lee and Mykland test?

**Comment by algoquant** [comment]
Yes, I'll be adding jump detection tests to the package.  I'll be making some big upgrades to the package this Summer.

**Comment by waynelapierre** [comment]
By the way, R is constrained by RAM while TAQ data are typically much larger than RAM capacity. Do you have any plan of integrating your package with some big data tools in R, like Sparklyr?

**Comment by algoquant** [comment]
I'm looking at package fst for providing fast random access to very large datasets on SSD:
http://www.fstpackage.org/
https://github.com/fstpackage/fst

Besides that, I plan to add more functions which rely on packages Rcpp, RcppArmadillo, and data.table.  Speed is important. 

Have you looked at package highfrequency?

I will appreciate your future interest and suggestions.

**Comment by waynelapierre** [comment]
I have used the highfrequency r package, but it is too slow and can only deal with small data sets. 
I personally think fst and data.table are the right direction, and I have saved all my financial data in fst format and use data.table to work on them. The speed of fst and data.table is great, but
you still need to work out how to deal with the RAM limit. 

I have thought about another two big data tools that may be suitable for data like TAQ, which are MonetDB and clickhouse. They are comparable to kdb+ but are open source (clickhouse should be faster than kdb+).

**Comment by algoquant** [comment]
The package fst allows random access to very large data frames stored in compressed data files in the .fst format.  Below is a script to illustrate it:

# Coerce TAQ xts to a data frame
library(HighFreq)
t_aq <- HighFreq::SPY_TAQ
t_aq <- as.data.frame(t_aq)
class(t_aq)
# Coerce data frame to a data table
data.table::setDT(t_aq, keep.rownames=TRUE)
class(t_aq); head(t_aq)
# Get memory size of data table
format(object.size(t_aq), units="MB")
# Save data table to .fst file
fst::write_fst(t_aq, path="C:/Develop/data/taq.fst")
# Create reference to .fst file similar to a data frame
fs_t <- fst::fst("C:/Develop/data/taq.fst")
class(fs_t)
# Memory size of reference to .fst is very small
format(object.size(fs_t), units="MB")
# Get sizes of all objects in workspace
sort(sapply(mget(ls()), object.size))
# reference to .fst can be treated similar to a data table
dim(t_aq); dim(fs_t)
fst:::print.fst_table(fs_t)
# Subset reference to .fst just like a data table
fs_t[1e4:(1e4+5), ]

**Comment by waynelapierre** [comment]
The reason you could do this is that t_aq is smaller than RAM at the first place. Let's say I have a data set that is larger than RAM and is in txt format. How can I use the fst functionality if I cannot read it into R and then convert it into fst format?

**Comment by algoquant** [comment]
When you create a reference to an .fst file, the data frame is not loaded into memory.  The reference to the .fst file is small, even if the data is huge.  When you subset the .fst reference then just that data is loaded into memory.   So you can perform operations on small chunks of huge data frames that wouldn't fit into R memory.
That's the whole point of the fst package, to provide *random access* to huge data frames.

**Comment by waynelapierre** [comment]
To convert a txt file to fst file, I will need to read it into R first and then use the fst package. If this txt file is larger than RAM, then how could I convert it into fst format?

**Comment by algoquant** [comment]
Yes, you're correct that fst doesn't solve the problem of how to convert a huge txt/csv file that doesn't fit into RAM, into an fst file.  I also see that you and others have requested that and similar enhancements:
https://github.com/fstpackage/fst/issues/178
https://github.com/fstpackage/fst/issues/9

Would packages disk.frame or sparklyr solve this problem?  Or maybe Python Dask or Julia JuliaDB?

**Comment by waynelapierre** [comment]
disk.frame seems promising, but I guess the maintainers of fst and data.table may have more expertise in this issue. Hopefully they will come up with a good solution. Python Dask and JuliaDB are similar, but neither of them is as fast as data.table. Spark is more similar to a database, but I am not sure how it could be integrated with fst or data.table.

**Comment by algoquant** [comment]
Yes, so we'll have to wait for the fst enhancements.
