### ISSUE TITLE
unable to load shared object '/HighFreq/libs/x64/HighFreq.dll':   LoadLibrary failure

### ISSUE THREAD

**Issue by shicmao** [algoquant/HighFreq#6]
Hi, I am trying to install on Windows 10 machine using R-4.2.1 / Rtools42 / RStudio. R-4.2.1 is installed at C:\RQuant\RCore\R-4.2.1 and Rtools42 is installed at C:\RQuant\Rtools\rtools42.

But it happend such error:
_**

> Error: package or namespace load failed for 'HighFreq' in inDL(x, as.logical(local), as.logical(now), ...):
>  unable to load shared object 'C:/RQuant/RCore/R-4.2.1/library/00LOCK-HighFreq/00new/HighFreq/libs/x64/HighFreq.dll':
>   LoadLibrary failure:

**_ 

I really appreciate your great work and this package can help me a lot when dealing with high frequency data.

![LoadLibrary failure](https://user-images.githubusercontent.com/54984586/192104264-a7cec57b-beb8-49eb-b1d7-c34fabcbf845.png)

**Comment by algoquant** [comment]
I recently installed the HighFreq package on a Windows machine.  And several other Windows users were also able to install HighFreq on Windows machines.  So it must be something specific to your setup.
I see you're running R version 4.2.1.  Try updating the packages Rcpp and RcppArmadillo.

**Comment by shicmao** [comment]
> @shicmao I recently installed the HighFreq package on a Windows machine. And several other Windows users were also able to install HighFreq. So it must be something specific to your setup. I see you're running R version 4.2.1. Try updating the packages Rcpp and RcppArmadillo.

@algoquant 
I updated packages Rcpp and RcppArmadillo to the newst version, but still occuring the same error. I tried the version of R-4.1.3 with Rtools 40 but the result was the same as R-4.2.1. However, in R-4.0.2 with Rtools 40 it has be installed successfully. So I copyed this package to R-4.2.1 library directory and it can be used normally. By the way, I found exactly the same error when installing igraph 1.3.5 by source files which need compilation.

**Comment by shicmao** [comment]
> @shicmao I recently installed the HighFreq package on a Windows machine. And several other Windows users were also able to install HighFreq. So it must be something specific to your setup. I see you're running R version 4.2.1. Try updating the packages Rcpp and RcppArmadillo.

@algoquant 
I updated packages Rcpp and RcppArmadillo to the newst version, but still occuring the same error. I tried the version of R-4.1.3 with Rtools 40 but the result was the same as R-4.2.1. However, in R-4.0.2 with Rtools 40 it has be installed successfully. So I copyed this package to R-4.2.1 library directory and it can be used normally. By the way, I found exactly the same error when installing igraph 1.3.5 by source files which need compilation.

**Comment by algoquant** [comment]
@shicmao 
I have no explanation why you had a problem installing under R-4.2.1.  But I'm glad you solved it.  It's good to know it worked under R-4.0.2.  I will therefore close this issue.
Please let me know if you require any enhancements by opening another issue.
